import { Router } from 'express';
import { requireAuth } from '../../middleware/auth.ts';
import { db } from '../../db/index.ts';
import { tasks, auditLogs } from '../../db/schema.ts';

const router = Router();

// Endpoint for Main Brain to plan tasks
router.post('/plan', requireAuth, async (req: any, res) => {
  try {
    const user = req.user;
    if (!user?.organizationId) {
      return res.status(400).json({ error: 'User has no organization' });
    }

    const { goal } = req.body;
    
    // Simulate LLM decomposition
    const generatedTasks = [
      { title: `Analyze: ${goal}`, departmentId: null, status: 'Backlog', priority: 'High', riskLevel: 'low' },
      { title: `Execute: ${goal}`, departmentId: null, status: 'Backlog', priority: 'Medium', riskLevel: 'medium' },
      { title: `Review: ${goal}`, departmentId: null, status: 'Backlog', priority: 'Low', riskLevel: 'low' }
    ];

    // Insert to DB
    const newTasks = await Promise.all(generatedTasks.map(async t => {
      const [task] = await db.insert(tasks).values({
        organizationId: user.organizationId,
        title: t.title,
        description: `Autogenerated task by Main Brain for goal: ${goal}`,
        status: t.status,
        priority: t.priority,
        riskLevel: t.riskLevel,
      }).returning();
      return task;
    }));

    // Log the planning action
    await db.insert(auditLogs).values({
        organizationId: user.organizationId,
        action: 'Main Brain Planned Goal',
        actorUserId: user.id,
        metadata: { goal, generatedTasksCount: newTasks.length },
        riskScore: 20,
        outcome: 'success',
        timestamp: new Date()
    });

    res.json({ message: 'Goal decomposed successfully', tasks: newTasks });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Main Brain failed to plan goal.' });
  }
});

export default router;
