import { Router } from 'express';
import { requireAuth } from '../../middleware/auth.ts';
import { db } from '../../db/index.ts';
import { tasks, auditLogs, memoryRecords } from '../../db/schema.ts';
import { llmService } from '../../services/llmService.ts';

const router = Router();

// Endpoint for Main Brain to plan tasks
router.post('/plan', requireAuth, async (req: any, res) => {
  try {
    const user = req.user;
    if (!user?.organizationId) {
      return res.status(400).json({ error: 'User has no organization' });
    }

    const { goal } = req.body;
    let generatedTasks = [];

    if (llmService.isAvailable()) {
      generatedTasks = await llmService.planGoal(goal);
    }

    if (!generatedTasks || generatedTasks.length === 0) {
      // Fallback to simulated logic if no API key or LLM failed
      generatedTasks = [
        { title: `Analyze: ${goal}`, description: "Initial analysis", status: 'Backlog', priority: 'High', riskLevel: 'low' },
        { title: `Execute: ${goal}`, description: "Core execution phase", status: 'Backlog', priority: 'Medium', riskLevel: 'medium' },
        { title: `Review: ${goal}`, description: "Final review and audit", status: 'Backlog', priority: 'Low', riskLevel: 'low' }
      ];
    }

    // Insert to DB
    const newTasks = await Promise.all(generatedTasks.map(async (t: any) => {
      const [task] = await db.insert(tasks).values({
        organizationId: user.organizationId,
        title: t.title,
        description: t.description || `Autogenerated task by Main Brain for goal: ${goal}`,
        status: t.status || 'Backlog',
        priority: t.priority || 'Medium',
        riskLevel: t.riskLevel?.toLowerCase() || 'low',
      }).returning();
      return task;
    }));

    // Log the planning action
    await db.insert(auditLogs).values({
        organizationId: user.organizationId,
        action: 'Main Brain Planned Goal',
        actorUserId: user.id,
        metadata: { goal, generatedTasksCount: newTasks.length, usedLLM: llmService.isAvailable() },
        riskScore: 20,
        outcome: 'success',
        timestamp: new Date()
    });

    res.json({ message: 'Goal decomposed successfully', tasks: newTasks });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Main Brain failed to plan goal.' });
  }
});

// Endpoint for Main Brain to dynamically invoke external functions
router.post('/execute', requireAuth, async (req: any, res) => {
  try {
    const user = req.user;
    if (!user?.organizationId) {
      return res.status(400).json({ error: 'User has no organization' });
    }

    const { context } = req.body;

    if (!llmService.isAvailable()) {
      return res.json({ 
        action: 'simulated_fallback', 
        message: 'No API key provided. LLM execution context skipped.',
        context 
      });
    }

    const response = await llmService.evaluateContext(context);
    const functionCalls = response.functionCalls;
    let executionResult = null;
    let invokedFunction = null;

    if (functionCalls && functionCalls.length > 0) {
      const call = functionCalls[0]; // Take the first invoked function
      invokedFunction = call.name;
      
      // Simulate external function execution side-effects
      if (call.name === 'sendNotification') {
        executionResult = { sent: true, details: call.args };
      } else if (call.name === 'blockWorkflow') {
        executionResult = { blocked: true, details: call.args };
      } else if (call.name === 'approveAction') {
        executionResult = { approved: true, details: call.args };
      } else if (call.name === 'saveMemory') {
        // Automatically save insights or rules to memory
        const newRecord = await db.insert(memoryRecords).values({
          organizationId: user.organizationId,
          category: call.args.category || 'org',
          content: call.args.content || JSON.stringify(call.args),
          metadata: { title: call.args.title || 'Brain Insight', source: 'Main Brain Execution' }
        }).returning();
        executionResult = { savedMemory: true, id: newRecord[0].id, details: call.args };
      }

      await db.insert(auditLogs).values({
        organizationId: user.organizationId,
        action: `Main Brain Execution: ${call.name}`,
        actorUserId: user.id,
        metadata: { context, tool: call.name, args: call.args },
        riskScore: call.name === 'blockWorkflow' ? 80 : 30,
        outcome: 'success',
        timestamp: new Date()
      });

    } else {
      // LLM decided no action or returned text
      executionResult = { status: 'no_action_needed', output: response.text };
      
      await db.insert(auditLogs).values({
        organizationId: user.organizationId,
        action: `Main Brain Execution: Analyzed Context`,
        actorUserId: user.id,
        metadata: { context, output: response.text },
        riskScore: 10,
        outcome: 'success',
        timestamp: new Date()
      });
    }

    res.json({ 
      message: 'Execution context processed', 
      invokedFunction, 
      executionResult 
    });

  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Main Brain failed to process execution context.' });
  }
});

export default router;
